### ISSUE TITLE
开发时重启的watch的需求

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/pandora#120]

**Comment by angrycans** [comment]
typescript 项目  希望在src 目录代码修改后能自动重启服务 实时预览效果

**Comment by guangwong** [comment]
Watch 可以支持

**Comment by haoliqiang** [comment]
@guangwong 您好，同学，这个feature开发完了么，怎么使用呢

**Comment by czy88840616** [comment]
现在的方向是，把进程守护部分进行拆分，这样在开发时就不需要 pandora 的守护功能，这样开发阶段的自动重启就交给框架部分来做就行了。
