### ISSUE TITLE
处理带 scope 的包名

### ISSUE THREAD

**Issue by guangwong** [midwayjs/pandora#125]
直接把 scope 去掉应该就行了吧？

`@scope/projectName` -> `projectName`

**Comment by angrycans** [comment]
可以的    不过需要注意的是你们logs目录也要做这个去掉的操作 现在带scope的包 会生成一个scopename 文件夹

**Comment by angrycans** [comment]
希望尽快提供版本

**Comment by czy88840616** [comment]
版本迭代会经过 next -> latest 的流程来走，我们需要先在内部测试完才能切换到 latest 版本，望谅解。

**Comment by guangwong** [comment]
今天把这个变更发 next tag

**Comment by guangwong** [comment]
next tag 已经发布。

使用 `npm install pandora@next` 可以帮忙测试一下

**Comment by guangwong** [comment]
已经发布，latest: 1.6.23
