### ISSUE TITLE
支持应用添加本地调用链路埋点

### ISSUE THREAD

**Issue by mariodu** [midwayjs/pandora#128]
支持应用在链路中添加内部调用的埋点统计。

- [ ] startLocal
- [ ] endLocal

**Comment by myfjdthink** [comment]
虽然催进度很不应该，但是还是希望 @mariodu 可以先分享一下该功能的设计思路。

**Comment by mariodu** [comment]
你是要用这个功能吗？这个 api 现在我们有一个调整，稍后会有一个完整的规范出来。

**Comment by myfjdthink** [comment]
是的，部分业务需要用到这个功能，那我等完成的规范出来吧。

**Comment by mariodu** [comment]
规范我们内部已经订好了，在实现，最近一两周就可以放到外面来了。
