### ISSUE TITLE
赞一个

### ISSUE THREAD

**Issue by einsqing** [midwayjs/pandora#161]
不错不错，已经替换pm2和alinode。

**Comment by czy88840616** [comment]
感谢支持

**Comment by bgdsh** [comment]
@einsqing 是不是用了这个pandora就不用pm2之类的进程守护工具了？如果是的话，我也考虑换上了。另外请问，这个工具是否已经用在了生产环境上？

**Comment by danielsss** [comment]
@bgdsh Pandora 可以替换 pm2 ! 另外这个工具至少在ali是有应用生产环境

**Comment by guangwong** [comment]
@bgdsh 已经有N百个生产环境应用了。

还有就是，我们现在重构了一个 Pandora.js 2.0 版本基本上 ok 了（文档还在写），做了模块块拆分，更加易用了。

还有之前开源了 Sandbox 监控系统（放在了 github 上还没宣传，阿里内部有一个基于这个的 Node.js 监控系统），可以直接对接 Pandora.js 进行应用集群监控。

有兴趣一起试试看吗？

**Comment by bgdsh** [comment]
@danielsss @guangwong 
谢谢科普，那我试试看。先从1.x玩起吧。
我看了你们团队的网站，觉得你们的几个开源软件都很棒，赞一个。
