### ISSUE TITLE
有现成的docker 镜像么，需要前台启动参数来配合 Docker 

### ISSUE THREAD

**Issue by kingsqv** [midwayjs/pandora#164]
在ubuntu 16.04 上 start 模式 会卡住不动， dev 模式启动可以

**Comment by guangwong** [comment]
这个我需要复现一下...   您可以看一下 ~/logs/pandorajs/ 下面的日志文件吗？

Docker 基础镜像稍晚提供，先保持这个 Issue Open...

**Comment by guangwong** [comment]
我正在装 ubuntu 16.04

**Comment by kingsqv** [comment]
看了下 日志 有listen 7002 的错误，看来是端口已经占用了

**Comment by guangwong** [comment]
你在这个机器上也启动了 spring 吗，这个是个已知问题。

**Comment by kingsqv** [comment]
机器上 这个端口用给一个代理了，
我自己做了docker 镜像，app可能需要前台启动， pandora dev 这种方式 和 daemon 功能上是一样的么

**Comment by guangwong** [comment]
pandora dev 没有启动 daemon ，不一样的。。  看来要给 pandora start 加个前台启动的支持了...
我们公司用的 Docker 都是后台启动的，应该还好吧...  k8s 可能有点问题，这个还在支持。

**Comment by kingsqv** [comment]
后台启动的话，再用别的程序，保持docker 么

**Comment by guangwong** [comment]
要不先加个 ` && tail -f ~/logs/pandorajs/daemon_std.log ` ... 晚点提供一个前台启动的参数...

**Comment by einsqing** [comment]
什么时候支持docker？

**Comment by lingxuan630** [comment]
@guangwong 计划哪个版本可以支持前台启动？

**Comment by czy88840616** [comment]
目前没有太多时间在这方面的处理，精力花在配套的展示平台上了。如果可以的话，可以帮我们做一些这方面的工作：）
