### ISSUE TITLE
Trace 相关文档啥时候写完，以及文档质量欠佳

### ISSUE THREAD

**Issue by SLRXXX** [midwayjs/pandora#168]
好像只有链路几个页面没写了……然而就这么一直不完整么？

**Comment by guangwong** [comment]
@mariodu  有人来催了...

**Comment by SLRXXX** [comment]
另外文档中很多配置文件都没写明文件位置，以及配置文件里出现了大量引用没有出处的现象

**Comment by mariodu** [comment]
链路开发给用户自定义的功能，部分 API 还没有稳定，所以文档一直没有给出，近期会完善。

**Comment by czy88840616** [comment]
@SLRXXX 文档的问题可能因为都是开发工程师，思维比价清奇独特，难以理解，如果哪边不太读不通，欢迎指出或者直接帮我们提 Pr 修改，感谢。

**Comment by SLRXXX** [comment]
比如，#基础功能##日志管理
###日志目录结构下这个${loggDir}指的是哪个目录，从哪里配置
###日志相关的默认配置，下面的配置应该写在哪个文件

**Comment by SLRXXX** [comment]
#基础功能##配置文件
###默认的全局配置 下面的配置json写在哪个文件里，DefaultEnvironment之类的变量从何而来

**Comment by guangwong** [comment]
您说的现象的确存在... 关于全局配置相关的确是阐述的不够清晰，得改。 

以及我们现在的全局配置必须通过环境变量全局设置，也存在一些用户体验问题。 以后考虑在 /etc/* 路径下提供一个默认的配置文件地址。

**Comment by guangwong** [comment]
进行了小部分的补充与订正

http://www.midwayjs.org/pandora/zh-cn/monitor/trace.html

http://www.midwayjs.org/pandora/zh-cn/base/logs.html

http://www.midwayjs.org/pandora/zh-cn/base/global_config.html

**Comment by guangwong** [comment]
望再给提提意见，特别需要 VOC ... 
如果有时间以及方便的话，也帮我们看看英文的文档 http://www.midwayjs.org/pandora/en/ ...

**Comment by g0ne150** [comment]
我就想试下催一下会不会有用

催！

**Comment by czy88840616** [comment]
哈哈，因为这部分集团内部还有异议，早上还在开会讨论接口，所以还没有确定。。

**Comment by danielsss** [comment]
> 我就想试下催一下会不会有用
> 
> 催！

必须要玩命催！

**Comment by czy88840616** [comment]
九妹说月底会重构完，哈哈
Daniels.Sun <notifications@github.com>于2018年12月12日 周三上午9:46写道：
