### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by dalssoft** [midwayjs/pandora#179]
Hi. First, congratulations for this project! great work!

Does pandora support GraphQL requests? Usually a complex query can be parallelized in mutiples promisses. Does it handle such scenario?

**Comment by guangwong** [comment]
We also like GraphQL very much.
But I have not tested it yet, I'll test it and reply you.

**Comment by guangwong** [comment]
It's works with GraphQL.

I made a simple instance with express-graphql:

`server.js`
```javascript
const express = require('express');
const graphqlHTTP = require('express-graphql');
const { graphql, buildSchema } = require('graphql');

const schema = buildSchema(`
  type Query {
    taobao: String,
    baidu: String
  }
`);

const root = {
  taobao: async () => {
    const res = await urllib.request('https://www.taobao.com/');
    return res.data.toString();
  },
  baidu: async () => {
    const res = await urllib.request('https://www.baidu.com/');
    return res.data.toString();
  },
};

const app = express();

app.use('/graphql', graphqlHTTP({
  schema: schema,
  rootValue: root
}));

app.listen(4000);
```

Then run `pandora init`
```bash
$ pandora init server.js 
? Which type do you like to generate ? fork
** The procfile.js was auto generated to location /Users/Allen/Works/tmp/graphql/procfile.js **
```

Then run `pandora start` to start it and start the dashboard.

```bash
$ pandora start
Starting graphql at /Users/Allen/Works/tmp/graphql
graphql started successfully! Run command [ pandora log graphql ] to get more information

$ pandora start `pandora-dashboard-dir` --name 'dashboard'
Starting dashboard at /usr/local/lib/node_modules/pandora-dashboard
dashboard started successfully! Run command [ pandora log dashboard ] to get more information
```

Then access `http://127.0.0.1:4000/graphql?query=query+{taobao,baidu}` few times, and open the dashboard to see the traces. Yes, it is works.

![image](https://user-images.githubusercontent.com/629202/36968791-92a0b3e8-209e-11e8-9565-1aad8f0b09c1.png)

**Comment by jeasonstudio** [comment]
@guangwong  Thanks for this project.  
I think Pandora's support for graphql tracing is not enough, and graphql tracing is already in its [specs](http://facebook.github.io/graphql/October2016/).  
Until now I have not found a useful and open source tool to visualize trace my requests ([Apollo Engine](https://engine.apollographql.com) is not open source).  
If Pandora can do more in this area, it would be great!!  
Looking forward to your reply.

> reference:  
* [https://dev-blog.apollodata.com/tagged/apollo-optics](https://dev-blog.apollodata.com/tagged/apollo-optics)
* [http://facebook.github.io/graphql/October2016/](http://facebook.github.io/graphql/October2016/)
* [https://dev-blog.apollodata.com/exposing-trace-data-for-your-graphql-server-with-apollo-tracing-97c5dd391385](https://dev-blog.apollodata.com/exposing-trace-data-for-your-graphql-server-with-apollo-tracing-97c5dd391385)
* [https://github.com/apollographql/apollo-tracing](https://github.com/apollographql/apollo-tracing)
