### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Jamez312** [midwayjs/pandora#182]
I'm interested in beginning translating the project into Spanish and I was wondering if I could start pull requests of the files. Many thanks in advance!

**Comment by mariodu** [comment]
Of course, you can start a new branch to do this. The document content is in the docs directory. If you need any help, you can contact us at any time. Looking forward to your PR.

**Comment by mariodu** [comment]
Progress? @Jamez312

**Comment by Jamez312** [comment]
I started translating another repo, but due to personal project I haven't finished it or started this one. For the time being I could tell other friends that might be interesed in helping.

**Comment by mariodu** [comment]
Never mind. I just want to know what's going on.
