### ISSUE TITLE
change to 8.0.0

### ISSUE THREAD

**Issue by stanleyxu2005** [midwayjs/pandora#183]
https://github.com/midwayjs/pandora/blob/a04d7e302a660bfec4d4faf875409cf21ae83fe7/package.json#L46

If pandora requires nodejs 8.0.0, please upgrade this check

**Comment by czy88840616** [comment]
In fact pandora.js can running on node.js v6.0, and we wanted to build different version by typescript at beginning. However, it seems that this is not necessary, we will change this version to 8.0。
