### ISSUE TITLE
https://github.com/midwayjs/pandora-example-rest-crud 好像 pandora start 不了

### ISSUE THREAD

**Issue by chinanf-boy** [midwayjs/pandora#188]
示例失败

[https://github.com/midwayjs/pandora-example-rest-crud](https://github.com/midwayjs/pandora/wiki/Pandora.js---%E4%B8%93%E4%B8%9A%E7%9A%84-Node.js-%E5%BA%94%E7%94%A8%E7%9B%91%E6%8E%A7%E7%AE%A1%E7%90%86%E5%99%A8%EF%BC%8C%E9%98%BF%E9%87%8C%E5%BC%80%E6%BA%90#%E5%90%AF%E5%8A%A8%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84-mysql-crud-%E7%9A%84%E4%BE%8B%E5%AD%90)

---

Mac 电脑
我的步骤

1. `git clone ` 
2. cd pandora-example-rest-crud
3. `yarn`
4. `pandora start`
>Starting rest-crud at /********/pandora-example-rest-crud
Error: Daemon [ pid = 69285 ] Died unexpectedly with exit code 1 , signal null

---

**Comment by guangwong** [comment]
你是否有把 https://github.com/midwayjs/pandora-example-rest-crud/blob/master/t_user.sql 
这个建表 SQL 执行到你的 mysql 里面去...

**Comment by guangwong** [comment]
然后您可以运行一下 `cat ~/logs/pandorajs/daemon_std.log` 给我看一下输出吗？

**Comment by chinanf-boy** [comment]
## 你是说 Mysql 本身 需要启动吗？？

log
```
2018-03-05 17:54:14,361 ERROR 69285 nodejs.AssertionError [ERR_ASSERTION]: should setup current environment before using it
    at EnvironmentUtil.getCurrentEnvironment (/Users/lizhenyong/.config/yarn/global/node_modules/pandora-env/dist/EnvironmentUtil.js:17:9)
    at new FileMetricsManagerReporter (/Users/lizhenyong/.config/yarn/global/node_modules/pandora-metrics/dist/reporter/FileMetricsManagerReporter.js:14:72)
    at BaseMonitor.startMetricsReporter (/Users/lizhenyong/.config/yarn/global/node_modules/pandora/dist/monitor/Monitor.js:57:35)
    at BaseMonitor.start (/Users/lizhenyong/.config/yarn/global/node_modules/pandora/dist/monitor/Monitor.js:39:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
generatedMessage: false
name: 'AssertionError [ERR_ASSERTION]'
code: 'ERR_ASSERTION'
actual: undefined
expected: true
operator: '=='
pid: 69285
hostname: yobravedePP.local
```

**Comment by guangwong** [comment]
这个是  yarn 安装的问题，现在用 yarn 安装貌似有点问题。 我们依赖了 npm 的安装机制...

**Comment by guangwong** [comment]
还在复现与修复中

**Comment by chinanf-boy** [comment]
我试试-
卸载->`yarn global remove`
重装->`npm i -g `

**Comment by guangwong** [comment]
这个例子需要安装原来的这个实例项目的文档，修改 mysql 配置，和导入建表语句

 http://teknosains.com/i/simple-crud-nodejs-mysql

**Comment by guangwong** [comment]
如果要试试看的话，你可以先试着启动我们的 Dashboard ，如果这个 Dashboard 能启动的话，其他问题应该都不大了... 
<https://github.com/midwayjs/pandora-dashboard>

**Comment by chinanf-boy** [comment]
o - o 好 我试试

**Comment by chinanf-boy** [comment]
可以启动,了

我发现启动-`http://localhost:9081/` 之后

回到示例的目录
`https://github.com/midwayjs/pandora-example-rest-crud`

```
pandora start
```
运行居然正常了 🌈
`http://localhost:9081/` 也有 信息了💻
```
rest-crud [Running]At location /Users/****/Desktop/Example/js-example/node-example/pandora-example-rest-crud
Uptime: 7s 286msPID: 71320Restart Count: 0
```

**Comment by guangwong** [comment]
那些要调用 MySql 的接口也能运行吗？ 因为那个例子真的依赖 MySql ，XD... 如果不行的话就把那些建表的语句导入到 MySql 里面。。。
