### ISSUE TITLE
Can it be used on multiple server instances?

### ISSUE THREAD

**Issue by uyu423** [midwayjs/pandora#191]
I want to use it for AWS auto scaling. 
use it with a pandora-dashboard, but I wonder if I can use Socket or HTTP communication to pass data to a remotely located pandora-dashboard.
Looking at the source code, there is only interprocess communication. Is there any way to communicate outside?

**Comment by guangwong** [comment]
By default, the dashboard listens on http://127.0.0.1:9081, so u cannot access it from outside... but u can change this default settings via some environment variables, show in below. 

```bash
pandora start --name dashboard --env "DASHBOARD_PORT=9081 DASHBOARD_HOST=0.0.0.0" `pandora-dashboard-dir`
```

`DASHBOARD_HOST=0.0.0.0` means the dashboard will listens on all IP addresses, so u can access it from outside. 

But that not security, anyone can access the dashboard without authorization. For this reason, we offer a basic HTTP auth feature via some environment variables, show in below.  

```
pandora start --name dashboard --env "DASHBOARD_AUTH=admin:password" `pandora-dashboard-dir`
```

Will this meet ur needs ?

If not, we have recently prepared to develop a private cloud platform to manage and monitor all distributed Pandora.js instances. That will started from next financial year of our company( April or May ).

**Comment by guangwong** [comment]
We already has use current version Pandora.js built a private cloud platform in our company. If u want to known the detail of this part. @mariodu will introduce that to u.

**Comment by uyu423** [comment]
@guangwong Thank you for your kind explanation.
But what I want to do is to see the Node.js application information from several physically separate servers in one dashboard?
Internally it is verified to use the process communication to get the Node.js application information. I wonder if I can provide process information to the dashboard via HTTP communication or Socket.

**Comment by mariodu** [comment]
Pandora.js will log all data it made to log, you can find the implements in pandora-metrics/reporter. So, in our production environment, we use collectors to collect logs in servers, and save them at a storage, like opentsdb and other bigdata storage, and export apis from a application to query data for dashborad.

So, you can follow our plan, use AWS's components to implement the architecture. And, you can change dashborad data query api to yours. But, remote debug and log display may have problem, @guangwong can provide some advice to do it.

By the end of the month, we will produce a RFC for private cloud. Welcome to suggest, participate in the discussion, and improve this standard together.

@guangwong @uyu423 @czy88840616

**Comment by uyu423** [comment]
@mariodu Thanks for the explanation. Do you have any examples for Pandora remote logging?

**Comment by mariodu** [comment]
@uyu423 You mean send the logs to another place through the network?

**Comment by uyu423** [comment]
@mariodu  That's Right. I would like to see logs from Server B on the Pandora Dashboard on Server A. If possible, I would like to see multiple server logs in one Pandora dashboard.

**Comment by mariodu** [comment]
You can get to know the syslog, it's a original linux log format. And Logstash or Filebeat as a log collector client. @uyu423

**Comment by guangwong** [comment]
Pandora dashboard basically cannot see logs from other server. 

The backend of pandora-dashboard has depended on the Actuator Server of Pandora.js, the Actuator Server can only listens on 127.0.0.1 for security reason. that means the Actuator Server cannot access from outside. 

Currently u can only start pandora-dashboard for each server.

Manage and monitor a server cluster( that also the multiple servers you're talking about ) in one dashboard is the goal of next financial year ( starts by April or May ). that goal and the solution we called "private cloud platform".

So it's impossible to achieve your requirement, but in a few months it should be achieved.

**Comment by uyu423** [comment]
@guangwong Thank you for your kind reply. If a private cloud service is launched, is it a paid service? If you have a paid service, do you planning to offer this feature free or open source?

**Comment by guangwong** [comment]
@uyu423 

It must be open source, and you can deploy it on your server.
Maybe we will deploy a public cloud service in the future for charge, but it's not very sure.
For our company, the ROI may not be high, we pay more attention to the influence of open source.

**Comment by uyu423** [comment]
@guangwong That's very nice news. Thank you. I think it is a very good decision. I'll wait until the feature is released. Are your next financial year April 2018?

**Comment by czy88840616** [comment]
@uyu423 That's right, we will begin develop this feature from April 2018 ：）

**Comment by uyu423** [comment]
@guangwong @mariodu @czy88840616 

Thank you everyone who gave a comment. Let 's see us again in April 2018. At that time I wish I could contribute something.

**Comment by uyu423** [comment]
@czy88840616 @guangwong 
Not yet available?  If not, what is the release date? I am waiting.
