### ISSUE TITLE
有 egg 接入 pandora 的方案吗

### ISSUE THREAD

**Issue by ImHype** [midwayjs/pandora#194]
egg 也是通过 scripts 的方式启动的，并且有自己的进程管理方案，两者能否整合？

**Comment by guangwong** [comment]
这个还在和 Egg 讨论中，不过依然可以用。

首先，在项目根目录定义启动文件：

`server.js`

```javascript
const egg = require('egg');

const workers = Number(process.argv[2] || require('os').cpus().length);
egg.startCluster({
  workers,
  baseDir: __dirname,
});
```

然后用 `pandora init server.js`，然后 `pandora start`。

**Comment by a526672351** [comment]
@guangwong 最好能和egg-script启动插件结合，因为经常在node xx.js 带参传输，子进程是获取不到的。

**Comment by zenjava** [comment]
启动时候，一定要记得选fork模式。不然会启动失败。

**Comment by huanglong** [comment]
@guangwong 

> 这个还在和 Egg 讨论中，不过依然可以用

这个有结论么，我们有十几个 Node 应用在用 Egg，runtime 已经接入了 alinode，需要一个更上层的监控台，有 Egg 与 Pandora 结合使用的最佳实践么?

**Comment by czy88840616** [comment]
@huanglong 内部我们也是这样使用的，光有 pandora 的数据以及现有的 dashboard 的展示是完全不够的，在内部 pandora 有配套一个自己的应用级别的平台叫做 sandbox，我们会在8月左右进行开源。

**Comment by zxrhu1314** [comment]
为什么我使用可视化pandora-dashboard-dir成功启动项目，也没报错，就是访问不到接口。不使用可视化工具一切正常

**Comment by zxrhu1314** [comment]
@guangwong 数据可视化工具，部署在远程服务器上，在本地能通过IP加端口访问吗。我试了一下在服务器上能拿到响应
curl http://127.0.0.1:9081

      <html>
        <head>
            <title>Pandora.js Dashboard</title>
        </head>
        <body>
            <div id="DUMP_APP_HERE" ></div>
            <script src="/public/bundle.js" ></script>
        </body>
      </htmljw>
但是在本地浏览器上无法响应。

**Comment by guangwong** [comment]
@zxrhu1314  参考这个

https://github.com/midwayjs/pandora/issues/255#issuecomment-400896420

**Comment by hzz780** [comment]
> 最好能和egg-script启动插件结合

> 这个有结论么，我们有十几个 Node 应用在用 Egg，runtime 已经接入了 alinode，需要一个更上层的监控台，有 Egg 与 Pandora 结合使用的最佳实践么?

伸手党同求，pandora + egg + alinode最佳实践....
