### ISSUE TITLE
not able to start on mac

### ISSUE THREAD

**Issue by xiaozhongliu** [midwayjs/pandora#198]
not able to start on mac, please help.
pandora: v1.8.13
node: v8.9.4
![image](https://user-images.githubusercontent.com/17674404/37254911-c6347eca-257f-11e8-9c7a-ed13acc6446c.png)

**Comment by xiaozhongliu** [comment]
will still freeze when executing with sudo
![image](https://user-images.githubusercontent.com/17674404/37254963-acf26548-2580-11e8-91cb-fb0810b39212.png)

**Comment by guangwong** [comment]
can u run ` cat ~/logs/pandorajs/daemon_std.log`, and paste the output for me ?

**Comment by czy88840616** [comment]
Is there any other update?

**Comment by xiaozhongliu** [comment]
all the content:
Pandora restful service start at http://127.1:7002
Pandora restful service start at http://127.1:7002
Pandora restful service start at http://127.1:7002
Pandora restful service start at http://127.1:7002
Pandora restful service start at http://127.1:7002
Pandora restful service start at http://127.1:7002
Pandora restful service start at http://127.1:7002
Pandora restful service start at http://127.1:7002

**Comment by xiaozhongliu** [comment]
any further help? I can share my desktop via QQ to reproduce if u need.

**Comment by guangwong** [comment]
可以啊... 怎么联系？

**Comment by czy88840616** [comment]
启动问题还挺复杂，可以提交一个最小的可复现版本的仓库，我们看下是应用问题还是环境的问题。

----

**Comment by guangwong** [comment]
有段时间没更新了这个 issue ，先关了。
