### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command [Windows 10]

### ISSUE THREAD

**Issue by dvgamer** [midwayjs/pandora#206]
```
pandora start --name dashboard --env "DASHBORAD_PORT=9081 DASHBOARD_HOST=0.0.0.0" --npm pandora-dashboard
```
** Resolve pandora-dashboard to C:\Users\Sentinal\AppData\Roaming\npm\node_modules\pandora-dashboard **
Starting dashboard at C:\Users\Sentinal\AppData\Roaming\npm\node_modules\pandora-dashboard
dashboard started failed, Error: Command failed: C:\Program Files\nodejs\node.exe  -e 'require("C:\Users\Sentinal\AppData\Roaming\npm\node_modules\pandora\dist\application\ProcfileReconciler.js").ProcfileReconciler.echoStructure({"appName":"dashboard","appDir":"C:\\Users\\Sentinal\\AppData\\Roaming\\npm\\node_modules\\pandora-dashboard","globalEnv":{"DASHBORAD_PORT":"9081","DASHBOARD_HOST":"0.0.0.0"}}, "C:\\Users\\Sentinal\\AppData\\Local\\Temp\\01533d9d-9a27-476d-8504-cab260a381c8"); process.exit()'
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by czy88840616** [comment]
like #187

**Comment by guangwong** [comment]
Duplicate with  #162
