### ISSUE TITLE
异常

### ISSUE THREAD

**Issue by pengliheng** [midwayjs/pandora#207]
![image](https://user-images.githubusercontent.com/14355994/37552939-615563d8-29f9-11e8-81b1-a846ca0e59a7.png)

**Comment by czy88840616** [comment]
和 yarn 一起使用的异常比较多，比如 #187

单独使用有问题吗？

**Comment by pengliheng** [comment]
没有，线上的腾讯云服务器跑起来了，没有问题，后台可视化dashboard也可以打开，没有问题，就是本地小米笔记本跑不起来，，win10，用vscode集成git跑的

**Comment by guangwong** [comment]
Windows 还没有支持，已经记录在 Issue  #162 。我现在把这个 Issue 关了，不再重复记录
