### ISSUE TITLE
Report data to PinPoint(a apm system)?

### ISSUE THREAD

**Issue by g0ne150** [midwayjs/pandora#212]
Asking for help.
Any advise for implementation?

Thanks.

**Comment by czy88840616** [comment]
We don’t know much about the pinpoint platform。If it provides some APIs for report by outside, maybe you can use `CustomReporter` to support custom report，like [open-falcon reporter](https://github.com/midwayjs/pandora-reporter-open-falcon).

**Comment by g0ne150** [comment]
I think `pandora-reporter-open-falcon` is a great idea, however I still can't figure out how to implement `pandora-reporter-open-falcon` on pandora.

Is there any where or any document that I can find about how?

**Comment by czy88840616** [comment]
If you want to implement a reporter for pandora, maybe need [doc](http://www.midwayjs.org/pandora/zh-cn/monitor/report.html) and [simple](https://github.com/midwayjs/pandora/blob/master/packages/metrics/src/reporter/TraceReporter.ts).

**Comment by g0ne150** [comment]
I'm confused, [TraceReporter](https://github.com/midwayjs/pandora/blob/master/packages/metrics/src/reporter/TraceReporter.ts) dose not export by "pandora-metrics/index.ts" so I can't import it by `require("dorapan")`

I don't think [doc](http://www.midwayjs.org/pandora/zh-cn/monitor/report.html) has answer
I doesn't find it in [global_config](http://www.midwayjs.org/pandora/zh-cn/base/global_config.html) either.

Could you just show me how to implement a reporter for pandora

**Comment by czy88840616** [comment]
不不，你不需要用到  TraceReporter，也不需要 require('dorpan')。。。

在自定义reporter上，其实是覆盖 pandora 的全局配置，使用[全局配置覆盖](http://www.midwayjs.org/pandora/zh-cn/base/global_config.html)就好。

```
PANDORA_CONFIG=./config.js pandora start .
```

```js
// in config.js
const YourRepoerter = require('xxxReporter');

module.exports = {
  reporter: {
    file: {
      enabled: false,
    },
    yourRepoerterName: {
      enabled: true,
      target: YourRepoerter,
    }
  }
}
```

这样就可以了

**Comment by g0ne150** [comment]
多谢兄得。。。
