### ISSUE TITLE
dashbard无法访问。

### ISSUE THREAD

**Issue by zenjava** [midwayjs/pandora#213]
![image](https://user-images.githubusercontent.com/12181571/37806623-fa59d4e8-2e7b-11e8-8acb-8fffe8cc3336.png)
请问这是什么原因？
还有，我用sudo的方式执行就不会报错。
但是我启动的目标应用是有起来，但是监控面板访问还是空的。

**Comment by zenjava** [comment]
先stop掉，然后重新启动就可以了。

**Comment by czy88840616** [comment]
看起来是dashboard之前已经启动了。。
