### ISSUE TITLE
建议采用center-agent模式

### ISSUE THREAD

**Issue by hstarorg** [midwayjs/pandora#216]
每台机器上，只需要使用agent来启动应用

将所有数据，汇总到center中，统一查看与分析

**Comment by czy88840616** [comment]
恩，模式是没问题的，pandora本身就是类似一个agent模式，除了预计算之外，同时会将数据上报到其他平台，除了现在的 dashboard 单机之外，我们有其他的方案，内部已经成熟，我们正在想办法提供到外部。#191 这里也讨论过相应的事情，只能说 pandora 是开源的第一部分，后面还有一些相应的配套还在含苞待放。

**Comment by hstarorg** [comment]
感谢，很好的东西。初期可以借鉴一些PM2的功能点

**Comment by czy88840616** [comment]
恩，如果觉得pm2的哪些东西特别有用，也欢迎提PR 👍

**Comment by czy88840616** [comment]
本 issue 由于长期未更新并暂时 close，如果后期有变化可以 reopen 继续讨论。

**Comment by hstarorg** [comment]
Ok,tks~
