### ISSUE TITLE
链路trace没有数据

### ISSUE THREAD

**Issue by Congeek** [midwayjs/pandora#225]
pandora.js 和 dashboard都启动了，但是没有看到链路数据
pandora是cluster方式启动，pandora.js和dashboard都是默认配置
一直没看到trace数据，请问下可能的原因是啥

![wx20180412-105215](https://user-images.githubusercontent.com/7792757/38654054-266c5ba4-3e40-11e8-8bc8-9a4da68c5103.png)
![wx20180412-105302](https://user-images.githubusercontent.com/7792757/38654092-43e2c240-3e40-11e8-84e4-a225bceb05c0.png)

**Comment by guangwong** [comment]
@mariodu  看看，有啥排查的方法吗？

**Comment by mariodu** [comment]
有 http 调用嘛？

**Comment by Congeek** [comment]
@czy88840616 
trace:
`{"data":{"count":0,"items":[]},"timestamp":1523512050525,"success":true,"message":""}`

daemon:
`{"data":{"versions":{"http_parser":"2.7.0","node":"8.9.4","v8":"6.1.534.50","uv":"1.15.0","zlib":"1.2.11","ares":"1.10.1-DEV","modules":"57","nghttp2":"1.25.0","openssl":"1.0.2n","icu":"59.1","unicode":"9.0","cldr":"31.0.1","tz":"2017b","pandora":"1.8.17"},"cwd":"/data1/node/frontend_service_16666","pid":13726,"uptime":13338.461,"loadedGlobalConfigPaths":["/usr/local/lib/node_modules/pandora/dist/default.js"],"loadedEndPoints":["daemon","error","health","info","process","metrics","trace"],"loadedReporters":["file"]},"timestamp":1523512039660,"success":true,"message":""}`

**Comment by czy88840616** [comment]
trace 接口是空的，的确没有数据，同时trace是开的 @mariodu

**Comment by czy88840616** [comment]
@Congeek 有使用 production 环境启么？

**Comment by Congeek** [comment]
@czy88840616  试过用pdocution，也是没有

**Comment by czy88840616** [comment]
如果用 process.env.NODE_ENV = production，采样率开启，会跌倒 10% 的概率，因为本地流量不大，所以基本上采集不到

**Comment by Congeek** [comment]
@czy88840616 之前没设置node_env的话，默认会是development吗？那时也是没有数据,原来项目用的pm2会不会影响到？

**Comment by czy88840616** [comment]
如果 start 的话默认好像的确就是 production，我去确认下

**Comment by mariodu** [comment]
server 是如何监听的，理论上通过 http.createServer 监听的，都应该会有 trace

**Comment by czy88840616** [comment]
我试了下 pandora start 是不会设置 NODE_ENV 的，pandora dev 启动默认会设置 local，这个可以打印下 process.env.NODE_ENV 看看

**Comment by mariodu** [comment]
node_modules/pandora-hook/dist/patch/HttpServer.js#79
你在这附近输出下日志，看有没有执行到，这里面我忘了加 debug。

**Comment by Congeek** [comment]
只找到pandora.js这个文件夹，没有pandora-hook，是不是有问题。。  @mariodu

**Comment by Congeek** [comment]
@guangwong 怎么设置启动的端口，例如我项目限定在13333和13334两个端口，要怎么配置

**Comment by mariodu** [comment]
额，那 node_modules/pandora/node_modules/pandora-hook 有嘛？

**Comment by czy88840616** [comment]
@Congeek 你是说 http://127.1:7002/daemon 这种端口？

通过覆盖默认的端口配置来修改。http://www.midwayjs.org/pandora/zh-cn/base/global_config.html

**Comment by Congeek** [comment]
@czy88840616  例如之前项目用pm2启动时会运行这个配置，pandora怎么加入，默认配置里面好像没这些项
```
var config = {
    "apps":[
        {
            "name"        : "frontend_service_" + process.env.START_PORT,
            "script"      : "./bin/www",  // 实际启动脚本
            "cwd"         : "./",  // "当前工作路径"
            "node_args"   : "--harmony", // node运行模式
            "max_memory_restart": "1024M",
            "instances"   : "2",
            "exec_mode"   : "cluster",
            "watch": false,
            "error_file" : "./logs/pm2_errors.log",  // 错误日志路径
            "out_file"   : "./logs/pm2_out.log",  // 普通日志路径
            "log_date_format":"YYYY-MM-DD HH:mm Z", //日期格式
            "env": {
                "NODE_ENV": "production",
                "PORT":     process.env.START_PORT,
                "SERV_ENV": "official"
            },
            "env_dev": {
                "NODE_ENV": "development",
                "PORT"    : process.env.START_PORT,
                "SERV_ENV": "test"
            }
        }
    ]
}

module.exports = config;
```

**Comment by Congeek** [comment]
@mariodu 只看到这些
<img width="450" alt="wx20180413-094506 2x" src="https://user-images.githubusercontent.com/7792757/38712615-772a96a4-3eff-11e8-8fd6-23ff327ecc9e.png">

**Comment by mariodu** [comment]
在 dist/patch/HttpServer.js#79 加一个输出，看下有没有调用到？

**Comment by guangwong** [comment]
@Congeek  您是说 PORT 这种环境变量吗？ 

具体参考，
http://www.midwayjs.org/pandora/zh-cn/base/procfile_mode.html
http://www.midwayjs.org/pandora/zh-cn/process/process_std.html 。

在 procfile.js 中类似下面的样子
```
pandora.process('a').env({
   ENV_VAR: 'envValue'
});
```

**Comment by Congeek** [comment]
@mariodu  没有调用到，我现在改了下procfile.js的配置来启动应用，看list里已经启动成功了，但是页面打不开，看日志也没有具体报错日志，有什么办法调试？

```
'use strict';

module.exports = (pandora) => {

  pandora
    .process('xm_worker')
    .scale('auto')
    .nodeArgs([
      '--harmony'
    ])
    .args([
      
    ])
    .env({
      NODE_ENV: "development",
      PORT: 12222,
      SERV_ENV: "test"
    });

  pandora
    .service('clusterX', class ClusterService {
      start() {
        require('./dist/app');
      }
    })
    // 不指定默认也是 worker
    .process('xm_worker')
    .publish();
}
```

**Comment by czy88840616** [comment]
@Congeek 最好能提供最小可复现用例吧，这样描述太难了。。

**Comment by Congeek** [comment]
@mariodu @czy88840616 可以了。。调了一天，换个浏览器发现打开了，真的很无语不知道为什么chrome不行，链路分析也有了;  现在想问下链路分析是怎么截断URL的，因为我们的api是类似于apiService/common?id=??的形式，在链路上看到是只有到common，分不出是哪个接口

**Comment by Congeek** [comment]
@czy88840616 Process [name = xm_worker, pid = 26411] Exit with code 1 and signal null
还有就是我整个pandora exit了，进程还在跑，堵住了端口。。怎么杀掉

**Comment by czy88840616** [comment]
@Congeek 可以直接 killall node

**Comment by czy88840616** [comment]
@Congeek 问题是否已经解决？

**Comment by Congeek** [comment]
@czy88840616 可以了，谢谢，我关了这个issue
