### ISSUE TITLE
如何自定义新增链路节点

### ISSUE THREAD

**Issue by ShaojieLiu** [midwayjs/pandora#228]

**Comment by lingxuan630** [comment]
请参考https://github.com/lingxuan630/pandora-custom-trace的写法。
我找到了两种方式可能实现自定义新增链路的，一种是在配置中增加hook，但是这个方法一直会报错，目前还没有时间找原因，另外一种就是直接扩展Patcher，获取TraceManager，这种方式比较暴力，但是有效。

**Comment by guangwong** [comment]
其实，现在可以这样获得 TraceManager 和 当前的 Tracer 对象。

```
const traceManager = require('dorapan').TraceManager.getInstance();
const currentTracer = traceManager.getCurrentTracer(); // 如果不在链路里会获得 undefined
```

**Comment by lingxuan630** [comment]
@guangwong 同学可以早点说嘛，我还花了两个小时去看源码的实现，伤心。
