### ISSUE TITLE
自定义日志配置覆盖失效

### ISSUE THREAD

**Issue by Congeek** [midwayjs/pandora#229]
按照文档说的利用命令行加载多配置，我覆盖修改了日志的默认存放目录，但是没有生效，日志依然存放在默认目录，是我的配置有误吗？

脚本:
![wx20180419-115212](https://user-images.githubusercontent.com/7792757/38970523-998ffd1a-43c8-11e8-9a3d-77a56fb54076.png)

覆盖的配置文件：
![wx20180419-115230](https://user-images.githubusercontent.com/7792757/38970602-062442b0-43c9-11e8-9205-98a45519b4de.png)

pandora-start,pandora-stop script命令：
![wx20180419-115245](https://user-images.githubusercontent.com/7792757/38970605-0a47371c-43c9-11e8-88c2-7bd84fe27cf8.png)

**Comment by Congeek** [comment]
@czy88840616 怎么知道配置是正常加载成功？有没有日志可以看？现在怀疑是配置没成功加载

**Comment by guangwong** [comment]
等我来复现一下

**Comment by guangwong** [comment]
我测试了下没有问题呀...

extConfig.js

```javascript
module.exports = {
  logger: {
    logsDir: '/Users/Allen/xd_testdir'
  }
}
```

然后

```bash
export PANDORA_CONFIG=`pwd`/extConfig.js
```

这个配置里面 require('pandora').appDir 是不能用的，这个会得到 undefined .

**Comment by Congeek** [comment]
@guangwong 那如果要指定到应用目录下呢，只能像你那样写吗？

**Comment by Congeek** [comment]
@guangwong 怎么调试配置是否加载成功呢？我也是差不多的配置，但日志还是存放在默认目录

**Comment by czy88840616** [comment]
我加个看启动配置的功能

**Comment by Congeek** [comment]
@czy88840616 请问看启动配置的功能增加了吗？现在还是没解决日志路径的问题

**Comment by czy88840616** [comment]
由于稳定性相关，不能切到 latest，可以先安装 next 版本

```
npm i pandora@next --save
```

在 start 之后会在 logs/run 目录下生成配置的内容，可以查看合并后的结果。

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/39162984-008f336a-47ab-11e8-8890-302fbc24be51.png)

版本：pandora@next `1.8.20`
位置：是在 pandora 的日志目录，一般在用户目录下 /logs

**Comment by Congeek** [comment]
@czy88840616 日志目录下没有看到有run这个目录，也没找到配置文件，确认过版本是1.8.20

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/39165321-8054bc54-47b6-11e8-87b9-50660eee83c7.png)

**Comment by guangwong** [comment]
要不我们远程桌面连接一个...

**Comment by Congeek** [comment]
@czy88840616 @guangwong 我再找另外一个项目重新接入试试，不行再找你们远程，因为是公司的项目，所以有点麻烦 .  
![wechatimg97](https://user-images.githubusercontent.com/7792757/39172868-ac3e3f06-47d5-11e8-80d2-8da14aeb8e89.jpeg)

**Comment by czy88840616** [comment]
好吧，这个issue我先关了，有问题再开。
