### ISSUE TITLE
建议pandora list命令可以显示出worker进程

### ISSUE THREAD

**Issue by Congeek** [midwayjs/pandora#231]
像pm2 list如果是用cluster模式启动的应用的话是可以看应用的worker进程的，pandora list只能看到master进程，想确认实例是否全部启动成功有点麻烦

**Comment by Congeek** [comment]
还有pandora list的restart count一直都是显示0，不会随着重启次数增加

**Comment by guangwong** [comment]
现在有一个 pandora ps 的功能， pandora ps <appName> 。 可以参考一下。

restart 现在统计的是异常重启次数，主动重启会清零。
