### ISSUE TITLE
上报数据后，如何从内存中清除数据防止重复上报和占用内存呢？

### ISSUE THREAD

**Issue by lingxuan630** [midwayjs/pandora#237]
```
class CustomTraceReport extends CustomReporter {
  constructor(actuatorManager, options = {}) {
    super(actuatorManager, options);
    this.vernier = {};
  }

  async report() {
   // ...
  }
}
```
上报后发现不断有叠加数据，按照这个方式，总有一天会把内存搞爆吧。

然后我看到配置上标明只缓存1000条数据，确认一下是不是超过1000后，前面的数据会销毁？

**Comment by guangwong** [comment]
@mariodu 看看

**Comment by lingxuan630** [comment]
@guangwong @mariodu 是否可以搞一个微信群作为pandora的沟通方式之一？

**Comment by guangwong** [comment]
@lingxuan630 现在有一个钉钉群，微信也可以搞... 

![image](https://user-images.githubusercontent.com/629202/39232396-c00194dc-489f-11e8-8ca1-67567adc5588.png)

**Comment by czy88840616** [comment]
@lingxuan630 对，只存最后1000条，先进先出

**Comment by stone-jin** [comment]
@lingxuan630 微信群有吗？

**Comment by czy88840616** [comment]
![https://img.alicdn.com/tfs/TB1HY5PvpooBKNjSZPhXXc2CXXa-674-896.jpg]()
