### ISSUE TITLE
mongodb nodejs driver 3.0.7 改变了 apm 的实现，导致 mongodb hook 失效

### ISSUE THREAD

**Issue by myfjdthink** [midwayjs/pandora#239]
pandora-hook 是通过在 mongodb.instrument 的 callback 来实现 mongodb 监听的。

在 mongodb v3.0.4 之前，callback 返回的 instrumentations 都还是数组。
```
var listener = require('../..').instrument(function(err, instrumentations) {
  instrumentations.forEach(function(obj) {
     // ...
  });
});
```

在 mongodb v3.0.7 ，instrument callback 返回的 instrumentations 变成了事件对象，目前还不知道 mongodb 为什么要做这个改动，文档还没有更新相关的说明，但是会导致 pandora mongodb hook 失效。
@mariodu 是否考虑对新版本 mongodb 做支持？

附：
mongodb 最新的 instrument 实现
https://github.com/mongodb/node-mongodb-native/blob/d6c34173a49ad49f67e06e37608ea4097bd7f8c8/lib/apm.js#L9

mongodb v2.x 的 instrument 实现
https://github.com/mongodb/node-mongodb-native/blob/344d1f5a18291a262e74f0addb40710f4d443926/lib/apm.js#L69

**Comment by mariodu** [comment]
这个我们已经关注到了，还在评估。

**Comment by mariodu** [comment]
https://github.com/mongodb/node-mongodb-native/blob/d6c34173a49ad49f67e06e37608ea4097bd7f8c8/CHANGES_3.0.0.md 具体变更原因
