### ISSUE TITLE
关于 Tracer 功能几点建议

### ISSUE THREAD

**Issue by myfjdthink** [midwayjs/pandora#240]
我最近在看 Node 这边链路追踪相关的实现，刚好 Pandora 就开源了，从 Pandora 里学习了不少链路追踪的知识，非常感谢各位的贡献。

在使用 Pandora 的过程中，发现我们这边业务中需要的几个功能点无法实现：

1. 绑定业务ID，例如 tracer 和 userId 绑定，然后可以在 tracer 面板中通过 userId 搜索，主要是为了知道某位用户实际请求了哪些业务。
2. 自定义 span 的 tags，例如 http 请求的 span，我们这边可能还需要记录 http request 的 query 、 body 和 response，希望能提供一个入口添加自定义 tag 。
3. 过滤 http 请求，看 http-server hook 的代码中已经预留了 requestFilter 来过滤，但是没有开放到自定义配置里。

**Comment by mariodu** [comment]
1. 可以通过扩展我们的基础实现来做到，本身都是可以继承覆盖的，因为这个对于不同的业务场景，需要的数据不一样，我们没法限制死。

2. 自定义的 tags 也是通过自定义实现的，因为我们也无法限制，只提供了最基本的数据。query 以及 body
 在 next tag 上已经实现。http server 的 response 暂时不太好记录。

3. next tag 已经开放。

**Comment by myfjdthink** [comment]
@mariodu 
next tag 是什么概念呢？

**Comment by czy88840616** [comment]
@myfjdthink 就是 npm 包的 next tag，你可以用 `npm install pandora@next --save` 来安装使用，由于是非 latest，暂时不能保证稳定性，我们会在一段时间后将 next 上的包切到 latest tag

**Comment by myfjdthink** [comment]
好的，我先看看实现

**Comment by czy88840616** [comment]
你可以覆盖 pandora 的配置来覆盖 pandora 的默认行为。
具体参考文档中的 `全局配置` 章节。

相应的配置类都是通过下面这个地方指定的。
https://github.com/midwayjs/pandora/blob/master/packages/pandora/src/default.ts#L164

**Comment by myfjdthink** [comment]
看起来是个可行的方案，我尝试下

**Comment by mariodu** [comment]
建议使用继承，通过配置，不要修改原型。

**Comment by myfjdthink** [comment]
@mariodu @czy88840616  我这边完成了第一个版本的拓展尝试，有些小问题，我直接发了个 PR，请直接看 PR 吧
#244
