### ISSUE TITLE
看了一下监控体系总览文档有点不解

### ISSUE THREAD

**Issue by 303182519** [midwayjs/pandora#251]
里面有个概念说到EndPoint 和 Indicator，想问一下，是EndPoint自动向各个Indicator获取数据，还是Indicator将数据自动上报到EndPoint？

**Comment by czy88840616** [comment]
两部分都有：

1、一般情况下，reporter 每分钟循环，调用每个 EndPoint.invoke 来拿数据，EndPoint 会通过 IPC 通道调用 Indicator.invoke 并返回数据
2、特殊情况，比如错误，因为不希望在每个进程里自己存储和做流控，以及考虑到实时性，做的是反向的上报，也就是从 indicator主动调用 report() 接口来发送到 EndPoint 端存储，reporter 取的其实是 EndPoint 中的缓存，这个机制目前适用于错误上报以及链路信息上报
