### ISSUE TITLE
这里接收参数使用this关键词合适吗？

### ISSUE THREAD

**Issue by jiuhuan** [midwayjs/pandora#256]
https://github.com/midwayjs/pandora/blob/b65dd1b318ed01c424c06ff78a1ca1c558213338/packages/hook/src/patch/shimmers/http-client/Shimmer.ts#L90

**Comment by mariodu** [comment]
`this` 为 http/https 导出的模块内容，应该不会产生过多的影响。不过用 `null` 可能好一些，欢迎提交 PR

**Comment by guangwong** [comment]
this 这种标记方法在 typescript 是指，给 this 标记类型，不是一个实际的参数。  https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters
