### ISSUE TITLE
如何在dashboard上监控多个应用

### ISSUE THREAD

**Issue by bluecoffee1013** [midwayjs/pandora#262]
我用docker部署了多个Node应用(相同的)，但如何让这些应用在同一个pandora dashboard上看到呢？看了一下文档，似乎每个node容器里面都得安装pandora。

如果要达到我想要的目标，是不是就得利用对外暴露的Restful API来自己做一套监控平台？

**Comment by czy88840616** [comment]
dashboard只限于单机，而跨机器监控的话，我们正在产出这样的方案，预估月底会有消息：）

**Comment by bluecoffee1013** [comment]
期待你们的好消息，这对运维来说是一个巨大的帮助！

**Comment by stone-jin** [comment]
@czy88840616 嗨，现在是9月初了，这个是这两天出来嘛？

**Comment by czy88840616** [comment]
@stone-jin delay 了。。预估到月底了。。我们正在抓紧时间做。。

**Comment by KentonYu** [comment]
现在的 dashboard 对于部署在 k8s 上的应用就很尴尬了，期待跨机器监控早日 release

**Comment by guangwong** [comment]
@KentonYu 现在针对 pandora 改版内部是做的差不多了，不过现在用了几个内部的数据库和日志采集产品，正在考虑怎么外部替换。。。

**Comment by KentonYu** [comment]
加油加油，这部分的确是个不小的工程 
希望尽早能看到 alpha/beta 版本，可以尽早用起来 🚀🚀

**Comment by guangwong** [comment]
话说你们都用什么采集日志，比如 logstash 这样的。

**Comment by KentonYu** [comment]
内部应用日志应该是通过 filebeats 存 ES 的，Node 现在才开始，调研发现这个开源项目
后续这个 dashboard 是会要求提供数据库地址（如 ES 之类的）？然后可以一键跑起来？

**Comment by guangwong** [comment]
@KentonYu 我们现在的方案没用 ES，不过需要一个采集和投递日志的组件。

现在的方案：

1. 链路
    1. 采集 Pandora.js 输出的文本日志，拆分链路，入库 Histore（我们内部的一个兼容 mysql 协议的列存储，外部希望用 MariaDB ColumnStore 之类产品代替，不知道有没有更好的推荐）
    2. 前端从 Histore 查数据，进行复杂的链路分析

2. Metrics
    1. 采集 Pandora.js 输出的文本日志，入库 TSDB
    2. 前端从 TSDB 查数据

3. 其他业务数据就是个普通 mysql ，如应用列表啥的

**Comment by bluecoffee1013** [comment]
@guangwong 目前我们后端是使用ELK的方案，觉得这个在行业内比较通用吧

**Comment by sophister** [comment]
在单机部署了下，太强大了，期待多机器的解决方案

**Comment by wadeDra** [comment]
这个close的下文有吗

**Comment by wadeDra** [comment]
@guangwong

**Comment by guangwong** [comment]
@wadeDra  https://github.com/midwayjs/sandbox-docker 这个你看看，配套 Pandora.js 2.0 的一个集群监控软件
