### ISSUE TITLE
hexo主题那个代码是在哪里呀

### ISSUE THREAD

**Issue by stone-jin** [midwayjs/pandora#267]

**Comment by czy88840616** [comment]
我看了一下好像是自己写的。。具体不详得问 @guangwong 。

ps：我准备改版了。。

**Comment by stone-jin** [comment]
@czy88840616 ,准备用什么改版呀？原来是hexo，现在呢？

**Comment by czy88840616** [comment]
Docsify, Docute, vuepress ，待定中。。
