### ISSUE TITLE
如何拿到request为post时,提取请求头中的post 表单参数。代码在哪里

### ISSUE THREAD

**Issue by runnerSnail** [midwayjs/pandora#269]

**Comment by runnerSnail** [comment]
node 中使用http.request (post) 提交请求，请求body里面会有一些data。我如何hook到这个requestclient参数呢

**Comment by mariodu** [comment]
是指这个吗？https://github.com/midwayjs/pandora/blob/master/packages/hook/src/patch/HttpServer.ts#L176

**Comment by runnerSnail** [comment]
我的意思是我有一个node应用，node 应用有可能作为客户端端请求别的接口
`    
// 我的node应用 controller层去请求一个接口
axios.post("http://www.baidu.com?aa=33&bb=3",{
            aaa:'ccc'
        }).then(res=>{
            console.log("post===>请求")
            // console.log(res.data)
        })`
我如何 hook 到这个 aaa:'ccc'  存起来

**Comment by runnerSnail** [comment]
get 是可以拿到的。post也可以吗，post里面的data 是放在body里面的吧

**Comment by mariodu** [comment]
在远程 http client 里拿 post 的 body 比较费劲，因为是 write 进去的。可以在上层的封装里获取，比较方便。

**Comment by mariodu** [comment]
可能要处理这个方法：https://github.com/nodejs/node/blob/058c5b81cdbabe8989a194ba5d388f4c230f4af6/lib/_http_outgoing.js#L566

**Comment by runnerSnail** [comment]
好的 感谢！
