### ISSUE TITLE
support debug with webstorm

### ISSUE THREAD

**Issue by smartheye** [midwayjs/pandora#279]
hi
I'd like to debug pandora application with WebStorm.
but I cannot see how to do it.
is there any plan that webstorm debug mode is supported by "pandora dev"?

**Comment by czy88840616** [comment]
https://midwayjs.org/pandora/guide/base/debug.html#ide%EF%BC%9Adebugging-in-webstorm-or-other-intellij-s-ide

Our document include debug for webstorm.
