### ISSUE TITLE
希望继续更新~

### ISSUE THREAD

**Issue by zuohuadong** [midwayjs/pandora#293]
这么好的项目，最近怎么不更新了？

**Comment by guangwong** [comment]
其实现在重构了一个 2.0 版本，https://github.com/midwayjs/pandora/tree/2.x 。
有更新，现在主要在阿里内部已经落地了，外部的还没宣传（文档也没写好）。

**Comment by zuohuadong** [comment]
> 其实现在重构了一个 2.0 版本，https://github.com/midwayjs/pandora/tree/2.x 。
> 有更新，现在主要在阿里内部已经落地了，外部的还没宣传（文档也没写好）。

好吧，也可以多考虑外部协作。加上 roadmap，有更多人来贡献也好一些。

**Comment by guangwong** [comment]
如果有 IM 的话，我们详细聊一下

**Comment by zuohuadong** [comment]
@guangwong 

wechat： z2858258

**Comment by KaroseLiu** [comment]
2.0 版本是否可用了，基于docker的项目是否可以无缝使用pandora?

**Comment by guangwong** [comment]
@KaroseLiu  可以用了，可以无缝使用。主要是默认前台启动了。 现在我们还配套了一个集群监控应用。  https://github.com/midwayjs/sandbox-docker

**Comment by guangwong** [comment]
@zuohuadong 晚点加你详细聊聊，最近加班比较多。
