### ISSUE TITLE
pandora list和pandora dashboard使用问题

### ISSUE THREAD

**Issue by winterZhao** [midwayjs/pandora#297]
在做监控方案调研的时候看到了pandora,所以尝试跑了pandora的起步进行尝试, 抱歉，不知道是文档太久没有更新，还是因为我操作有误，总体使用感觉有一些问题

环境

      macosx / centos7虚拟机
      node: v10.15.3/ v10.10.0
      Pandora: 2.1.0 (/root/.nvm/versions/node/v10.10.0/lib/node_modules/pandora/bin)

我用express-generator快速的启动了一个express项目,然后在www同级目录下`pandora init ./www`生成了procfile.js，但在启动过程中碰见了以下几个问题：

问题

1. 后台启动问题:  发现使用`pandora start -d `命令 后台启动和其他程序不太一样，其他程序后台启动的时候会输出一部分日志， 然后当再按回车键时日志就消失了，但是这个一直会有,只能关闭当前会话，再开一个新的会话, 当前会话已经无法再做其他事情了
能否做成和其他那样类似的效果，这样使用体验会好一些

2.  `pandora list` / `pandora ps` 完全没有效果,输入命令没有返回, 无论是前台还是后台，能否帮忙把pandora list产生返回所对应的 pandora start 命令发一下

3.  文档不全,目前只有init和start两个命令;

4.  无法退出,  我只能使用lsof配合kill -9, 强制退出，无法通过 `pandora stop`和`pandora exit`退出某个pandora进程或所有pandora进程;

5. 前后台模式，可能是被pm2习惯了，还是觉得默认后台模式 + 直接看日志 会好一些，
 
6. dashboard启动没有效果: `pandora start --name dashboard '/usr/local/lib/node_modules/pandora-dashboard/'`,启动后正常，但是浏览器访问9081端口没有效果

**Comment by czy88840616** [comment]
@guangwong

**Comment by guangwong** [comment]
2.x 的版本文档的确是缺失的，因为之前一直在落地公司内部，外部这些文档还没来得及补充。 如果你想体验的话，建议使用 1.x 的版本。 安装 npm i pandora@1.x.x。

**关乎 2.x 的问题**
1. 后台启动的能力是不健全的，因为现在容器化的时代后，后台启动被认为是一个不必要的功能。 你可以使用 pandora start & 来启动到后台。 -d 这个参数现在存在一些问题，还未修复。 
2. pandora-dashboard 是覆盖 1.x 版本的，2.x 配套了一个集群化的查看器 https://github.com/midwayjs/sandbox-docker 。 单机查看 2.x 暂时没有。


2.x 的外部使用使用文档需要补充，这一点的确很不友好。  也欢迎一起来补充。

**Comment by winterZhao** [comment]
感谢你的及时回复，使用1.x版本配合官方文档确实能够成功的跑起项目，谢谢!
但跑pandora-dashboard的时候有个报错

      pandora start `/usr/local/lib/node_modules/pandora-dashboard` --name dashboard

      -bash: /usr/local/lib/node_modules/pandora-dashboard: is a directory
     Starting dashboard at /Users/xxx/project/ansiable/test
     dashboard started failed, Error: Start failed, looks like not a pandora project, in appDir /Users/xxx/project/ansiable/test

请问这个是什么原因

**Comment by guangwong** [comment]
@winterZhao  O__O "…， `/usr/local/lib/node_modules/pandora-dashboard` 换成 pandora-dashboard 的目录吧

**Comment by winterZhao** [comment]
好的好的，我明白了，谢谢你，原来就是使用`pandora start --name dashboard `pandora-dashboard-dir`这句话就可以了，我多想了，麻烦了
