### ISSUE TITLE
pandora 支持从 Node 8 开始

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/pandora#30]

**Comment by czy88840616** [comment]
鉴于nodev8 已经 LTS 并停止 V6的更新，同时维护多个包的代码也会对代码造成一定的影响，是否可以从 8开始支持。

**Comment by welladamm** [comment]
+1

**Comment by guangwong** [comment]
6 应该还有不少生产环境在使用吧，我建议再支持一段时间

**Comment by welladamm** [comment]
@guangwong 这个原因我觉得出发点不对，照这个理论，v4 也有很多生产环境在用的，这并不意味着我们也要支持 V4。

**Comment by luin** [comment]
用 TypeScript 的话生成一份支持 v6 的版本应该不会很麻烦吧？如果比较麻烦就没有必要了

**Comment by czy88840616** [comment]
先以 8 为基准上，如果用户有强烈需求上6，再打6的包吧，我们内部保证两个版本都可用吧，毕竟一旦出了6，后续的推广维护，可能都会受一定的制约。
