### ISSUE TITLE
内存分析的疑问

### ISSUE THREAD

**Issue by wadeDra** [midwayjs/pandora#301]
想问问nodeMetrics是用来做什么场景的？跟alinode的内存溢出排查场景一样吗？

**Comment by guangwong** [comment]
基本上来说可以用来分析内存使用情况，基本上也就是内存溢出之类的吧

**Comment by wadeDra** [comment]
有截图吗  我看一下

**Comment by guangwong** [comment]
就是 Node.js 一些堆栈的情况丫，可以起到基础的观测。 比较要排查哪个对象造成的泄露，还是要依赖 alinode  一类的产品；

**Comment by wadeDra** [comment]
那还需要到阿里云上面才能查看么？还是直接可以看的到？

**Comment by czy88840616** [comment]
感谢支持，此项目已完成历史使命，不再更新。
