### ISSUE TITLE
局部安装pandora在应用内，在centos进入根目录pandora list没反应

### ISSUE THREAD

**Issue by lyseky** [midwayjs/pandora#303]

**Comment by guangwong** [comment]
用的是 1.0 还是 2.0 ？

**Comment by lyseky** [comment]
1.0

**Comment by guangwong** [comment]
首先 1.0 这个版本不希望长期维护了，现在的 2.0 版本的话，只有前台启动的功能，也就是只有 pandora start 到前台。 比较适合配合 Docker、K8S 这一类容器服务来使用；

然后 1.0 这个，你具体是怎么装的，怎么运行的  pandora list ，可以截图看看吗？

**Comment by lyseky** [comment]
"dashboard": "pandora start --name dashboard --env \"DASHBORAD_PORT=9081 DASHBOARD_HOST=0.0.0.0\" --npm pandora-dashboard"

**Comment by czy88840616** [comment]
感谢支持，此项目已完成历史使命，不再更新。
