### ISSUE TITLE
pandora是否会对APP性能造成影响？

### ISSUE THREAD

**Issue by halft0n** [midwayjs/pandora#306]
用pandora启动一个web app，是否会对app 的性能造成影响？具体影响有大概的数字吗，比如是５％，７％？

**Comment by mariodu** [comment]
会造成影响。目前基于 async-hooks 的链路性能损耗较多，主要在 promise 上性能较差，目前我们在应用上测试在 15% 左右，Node.js 社区也在积极优化这方面性能。关闭链路后基本对应用影响可忽略。

**Comment by wadeDra** [comment]
> 会造成影响。目前基于 async-hooks 的链路性能损耗较多，主要在 promise 上性能较差，目前我们在应用上测试在 15% 左右，Node.js 社区也在积极优化这方面性能。关闭链路后基本对应用影响可忽略。

怎么配置关闭链路？

**Comment by czy88840616** [comment]
感谢支持，此项目已完成历史使命，不再更新。
