### ISSUE TITLE
is "stop timeout" configurable?

### ISSUE THREAD

**Issue by zimtsui** [midwayjs/pandora#310]
version 1.10.6

is it fixed to be 5s or configurable?

O(∩_∩)O谢谢
@czy88840616 @guangwong

**Comment by guangwong** [comment]
it is not configurable for now.  but it can be adjusted. and we glad to see, if u make a your own PR.

**Comment by czy88840616** [comment]
Thanks for your support, this project has completed its historical mission and will not be updated.
