### ISSUE TITLE
macos 下除 `pandora start `可以使用外，其他都不好使

### ISSUE THREAD

**Issue by liSong5713** [midwayjs/pandora#313]
**遇到的问题：**
macos 下除 `pandora start `可以使用外，其他都不好使，如`pandora list `无反应

**pandorajs &nodejs version:**
Pandora: 2.2.0 
Node: v12.12.0

**运行环境：**
 `Distro: OS X 10.14.6
 Kernel: Darwin
 Uptime: 28 mins
 Shell: /bin/zsh
 Terminal: xterm-256color iTerm.app
 CPU: Intel Core i5-8259U CPU @ 2.30GHz
 Memory: 8 GB
`
麻烦帮忙看下？

**Comment by zzh948498** [comment]
linux乌班图比你多用一个init，其他也无反应

**Comment by czy88840616** [comment]
非常抱歉，由于原定的配套sandbox在社区部署非常困难，导致pandora这个东西无法快速部署，展现报表等，后续应该也很难在社区使用，建议使用其他同类产品替代（pm2 等），我们也会在其他地方标注。

**Comment by guangwong** [comment]
如上所说，现在 2.0 版本主要在集团内使用。现在文档是针对 Pandora.js 1.0 的，可以尝试安装 pandora@1.x.x；
