### ISSUE TITLE
该更新文档了

### ISSUE THREAD

**Issue by 18317252500** [midwayjs/pandora#314]
跟着文档走错误百出啊- -
pandora:2.2.0
node:v12.10.0

**Comment by czy88840616** [comment]
非常抱歉，由于原定的配套sandbox在社区部署非常困难，导致pandora这个东西无法快速部署，展现报表等，后续应该也很难在社区使用，建议不要再使用此工具，我们也会在其他地方标准。

**Comment by guangwong** [comment]
如上所说，现在 2.0 版本主要在集团内使用。现在文档是针对 Pandora.js 1.0 的，可以尝试安装 pandora@1.x.x；
