### ISSUE TITLE
如何使用v3

### ISSUE THREAD

**Issue by jimizai** [midwayjs/pandora#315]
之前尝试了v2.x版本的pandora 感觉很多有很多问题 最近看到了v3.0的tag 请教下如何能在本地尝鲜体验

**Comment by legendecas** [comment]
目前还没到可以使用的程度，整体还会有比较大的改动。会在后续的更新中，同步新版进展。

**Comment by zurmokeeper** [comment]
既然是一个半成品，在文档的开头请应该明显的提示开发者，不然装了以后这个又用不了那个又用不了，一看文档没有说是哪个版本的，一通操作最后发现全是无用功，本来对pandora很有兴趣，一盆冷水下来，什么都没有了。

**Comment by czy88840616** [comment]
感谢支持，此项目已完成历史使命，不再更新。
