### ISSUE TITLE
请问，如果我用pandora来管理定时任务可以吗？

### ISSUE THREAD

**Issue by aylizhiyuan** [midwayjs/pandora#318]
本司需要管理多个定时任务，定时任务一旦出现问题，可以及时报告和重启，请问pandora合适吗?

**Comment by czy88840616** [comment]
我觉得不是很合适...pandora主要做的是采集监控数据..

**Comment by aylizhiyuan** [comment]
> 我觉得不是很合适...pandora主要做的是采集监控数据..

你好，对于定时任务管理的话，你们有什么推荐使用的开源模块吗...
