### ISSUE TITLE
提供一个 Service 模板

### ISSUE THREAD

**Issue by zimtsui** [midwayjs/pandora#319]
以前 v1.0 的时候用过 pandora。pandora 将 script 抽象成一个有 start 和 stop
 方法的 service 类来解决优雅启停的问题，个人认为这种设计的优美程度吊打 pm2、foreverjs 等一众主流进程管理器。

虽然不知道为啥后来 pandora 停更了，但这种设计值得推广。于是我写了个 service 模板，专门适配 pandora，解决了以下问题

1. 允许 service 自己 stop 自己。
2. 优雅地嵌套 service
3. 优雅捕获 start 和 stop 方法本身抛出的错误
4. 可以将 service 转换为 script 来适配 pm2、foreverjs 等传统进程管理器

详见[Startable](https://github.com/zimtsui/startable)

**Comment by czy88840616** [comment]
感谢支持，此项目已完成历史实名，不再更新。
