### ISSUE TITLE
启动某一项目后报 TypeError: Promise.coroutine.addYieldHandler is not a function

### ISSUE THREAD

**Issue by guangwong** [midwayjs/pandora#38]
TypeError: Promise.coroutine.addYieldHandler is not a function
初步观察，cls-bluebird 这个模块里改写了 Promise.coroutine ，导致丢失 addYieldHandler 。

**Comment by guangwong** [comment]
Trace 也无法采集

**Comment by mariodu** [comment]
next 分支已提交临时修复。
相关模块更新需要 PR 合并。
https://github.com/TimBeyer/cls-bluebird/pull/17
