### ISSUE TITLE
优化现有进程创建结构

### ISSUE THREAD

**Issue by guangwong** [midwayjs/pandora#47]
调整进程结构，将现有 Master 调整为 ScaleMaster，scale 为 1 时只 Fork

**Comment by czy88840616** [comment]
画个图描述下，到时候放文档里

**Comment by guangwong** [comment]
![x](https://camo.githubusercontent.com/37f76e79f6169ec7381765edb0689579deaf5413/68747470733a2f2f696d672e616c6963646e2e636f6d2f7466732f5442316770785068677644384b4a6a7930466c58586167424658612d313739342d3839302e706e67)

**Comment by guangwong** [comment]
大致要做的变更如下，在未来 1.2.x 中支持进行，是一个向前兼容的变更：

1. ProcessBootstrap.ts、WorkerProcessBootstrap.ts
2. 将 ProcfileReconciler.getApplicationStructure 和 ProcfileReconciler.getComplexApplicationStructureRepresentation 彻底合并。现在是为了支持 fork 临时支持的。
3. fork 模式也会启动 WorkerContext （以及其子进程，需要通过 Spawn-wrap 处理），可以正常使用 IPC-Hub 等功能。 并将 WorkerContext 更名为 ProcessContext 以表通用性。
