### ISSUE TITLE
实现进程重启 Count

### ISSUE THREAD

**Issue by guangwong** [midwayjs/pandora#49]
比如 fork 一个 master-worker 的应用，无法统计到 worker 的重启的次数。
现在有采集 Process 的信息，路子是通的，可以搞一个。

**Comment by stanleyxu2005** [comment]
+1 

同时建议考虑几点
1. 如果启动时候就crash的重启策略
2. 使用到中途crash的重启策略
3. 在达到重启上限之后，依旧可以通过api重启进程
