### ISSUE TITLE
能否开放支持process signal相关的事件监听

### ISSUE THREAD

**Issue by kurten** [midwayjs/pandora#71]
比如：process.on('SIGTERM', () => {});
目前来看是没有开放相关的支持，能否支持一下呢？

**Comment by guangwong** [comment]
并不是不支持，现在 Pandora.js 监听了 SIGTERM ，处理完一些内部逻辑后自己做了 process.exit() 。我判断下，如果用户也监听了的话，就不自动 process.exit() 了，留给用户自己处理。

**Comment by stanleyxu2005** [comment]
原则上讲`process.on('SIGTERM'`可以多次触发的。但是如果谁在这个handling里面执行了`process.exit()`那么其他的listener就没有机会了。可以参考pm2在启动daemon的时候，配置一下，是否要在处理完signal执行退出。

至于捕捉信号，尤其是windows下，这里有一些谈论，并没有简单的实现方法。
https://github.com/Unitech/pm2/issues/3467
https://github.com/Unitech/pm2/issues/3254#issuecomment-368226031
https://github.com/laino/final-pm/issues/6
