### ISSUE TITLE
用户某些情况下无法直接 require('pandora') 和 require('pandora-*')

### ISSUE THREAD

**Issue by guangwong** [midwayjs/pandora#74]
1. 比如全局安装的情况下。
2. 就算本地安装，需要引用内部包时，比如 require('pandora-metrics') 时也需要用户 npm 安装，未来可能导致版本不一致的问题。

提出 3 个解决方案：

1. 让用户 require('dorapan')，A Mirror of Pandora，直接直接映射到全局的 Pandora。
2. 将全局的 Pandora 放到 NODE_PATH 中去，建议用户不要自行安装 pandora （如果已经全局安装）。
3. Hack 进 Node.js 的 require 机制，将 require('pandora') 强制为全局的 pandora。

个人倾向于 1 。

同时，pandora-metrics 的导出接口，由 require('pandora') 全部代理，用户不自行引用 require('pandora-metrics')，保证用户界面的单一。

**Comment by czy88840616** [comment]
如果应用中的，即要装 pandora 又要装 dorapan？

**Comment by guangwong** [comment]
还有一种思路是，应用启动时将全局的 pandora 直接 link 进去？

**Comment by guangwong** [comment]
@czy88840616 #80
