### ISSUE TITLE
需要依赖node版本8以上

### ISSUE THREAD

**Issue by Ahkari** [midwayjs/pandora#77]
我用node6版本无法启动成功。

`npm install n -g`
`sudo n 8.9.3`

到这个版本的node就可以使用了。

具体看了下之前报错的信息：

```JavaScript
/usr/local/lib/node_modules/pandora/dist/universal/LoggerBroker.js:57
async function backupLog(file, newName) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
````

应该是升级到  支持es2017的 的node版本，比如node 8.9.3，就ok了。

[NODE-GREEN](http://node.green/#ES2017-features-async-functions)

**Comment by czy88840616** [comment]
嗯，目前支持 node大于等于8.0，毕竟8.0已经是LTS版本了，而且性能好很多
Ahkari卡狸 <notifications@github.com>于2017年12月19日 周二下午8:31写道：

**Comment by czy88840616** [comment]
![image](https://user-images.githubusercontent.com/418820/34197097-eba9b190-e59f-11e7-98d6-a94f163c3f25.png)

**Comment by guangwong** [comment]
启动的时候加个提示吧
