### ISSUE TITLE
[Question] 后台常驻进程问题

### ISSUE THREAD

**Issue by solarhell** [midwayjs/pandora#79]
例子中有 `puppeteer`，是否可以认为常驻一个chrome进程不关闭会更高效？ 在这种情况下 我只有在服务下线的时候需要执行 `await stop()` 即 `await this.browser.close()`。
再或者实现一个常驻消费者，它需要与第三方（苹果APNs服务器、短信服务器）建立连接，这些有最佳实践吗？因为在我目前的实现中，是有一个连接池的概念的。
谢谢！

**Comment by guangwong** [comment]
1. 那个例子中，就是一个常驻的 background 进程里面有一个常驻的  PageSnapshot Service （基于  Puppeteer ） 。也就是您说的 `常驻一个chrome进程不关闭会更高效`。那个 `async stop()` 是服务下线时，才会调用的。 `async stop()` 是用于优雅下线（服务）的，参见：<https://zhuanlan.zhihu.com/p/32161351>

2. 关于连接池，推荐使用 [`Generic Pool`](https://github.com/coopernurse/node-pool)，继续以 Puppeteer 为例：[Puppeteer Pool](https://github.com/latesh/puppeteer-pool)。

**Comment by solarhell** [comment]
感谢解答！之前没有理解什么时候会执行到 `async stop()`，所以才产生了这样的疑问。
