### ISSUE TITLE
restart count 不断增加

### ISSUE THREAD

**Issue by dahuangfengda** [midwayjs/pandora#81]
我使用pandora start ./app.js这个命令启动，在pandora list发现出现多个PID，restart count 不断增加
<img width="929" alt="2017-12-21 9 59 09" src="https://user-images.githubusercontent.com/6766779/34258944-dfb5d70c-e625-11e7-8b2b-3834a054867a.png">

**Comment by dahuangfengda** [comment]
应该是多个进程都想去启动应用，但只有一个进程占用端口号，导致其他进程不断重启

**Comment by guangwong** [comment]
您好，Pandora.js 只支持通过 `procfile.js` 启动。
pandora start [path] ，path 需要是一个目录，并且该目录下有一个 `procfile.js` 文件。

如果 path 取值是一个文件时，我们在命令行做了一个功能，会自动生成一个 procfile.js 。
我刚才试了一下的确会出现问题，明天修复这个问题。

@czy88840616

**Comment by guangwong** [comment]
@czy88840616 如果用户只是想启动一个文件，类似：

> pandora start ./app.js 

自动生成 `procfile.js` 还是有点鸡肋... 有几个想法：

1. 一条道走到黑，只支持 `procfile.js`。
2. 增加提示，并提供 `pandora init ./app.js` 这样命令，自动初始化。
3. start 命令支持简单对于单个文件的 fork 和 cluster ，就像以前支持的一样。不过这个和我们的初衷有点违背。

**Comment by czy88840616** [comment]
如果提供多入口，里面的逻辑你也写过，其实挺麻烦，而且多个选择事实上并不友好，建议还是“一条道走到黑”，个人觉得只支持 procfile.js 就行了，毕竟命令行只是辅助，我们真正核心的进程编排还是依靠 procfile.js

**Comment by guangwong** [comment]
已经解决在 PR #82 
现在如下设计。

启动一个文件时进行提示（通过 `pandora start app.js` 或 `pandora dev app.js`）：
```bash
$ pandora start app.js 
Error: Pandora.js can only start a Pandora.js project directory, like [ pandora start ./ ]
You can use [ pandora init app.js ] to init a Pandora.js project
```

然后运行按照提示运行： `pandora init app.js`

```bash
$ pandora init app.js
? Which type do you like to generate ? (Use arrow keys)
❯ fork 
  cluster 
** The procfile.js was auto generated to location /xx/xx/procfile.js **
```

1. 最终执行 `pandora start`（默认工作目录） 或 `pandora start ./` 皆可
2. 最终执行 `pandora dev`（默认工作目录） 或 `pandora dev ./` 皆可

**Comment by guangwong** [comment]
#82 已经 merge，npm 已经发布 `pandora@latest`
